//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.32559.
// 
#pragma warning disable 1591

namespace csfiddle.csfiddle.IdeOne {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ideone_Service_v1Binding", Namespace="http://ideone.com/api/1/service")]
    public partial class Ideone_Service_v1Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createSubmissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubmissionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubmissionDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLanguagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback testFunctionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ideone_Service_v1Service() {
            this.Url = global::csfiddle.Properties.Settings.Default.csfiddle_csfiddle_IdeOne_Ideone_Service_v1Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createSubmissionCompletedEventHandler createSubmissionCompleted;
        
        /// <remarks/>
        public event getSubmissionStatusCompletedEventHandler getSubmissionStatusCompleted;
        
        /// <remarks/>
        public event getSubmissionDetailsCompletedEventHandler getSubmissionDetailsCompleted;
        
        /// <remarks/>
        public event getLanguagesCompletedEventHandler getLanguagesCompleted;
        
        /// <remarks/>
        public event testFunctionCompletedEventHandler testFunctionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ideone.com/api/1/service#createSubmission", RequestNamespace="http://ideone.com/api/1/service", ResponseNamespace="http://ideone.com/api/1/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] createSubmission(string user, string pass, string sourceCode, int language, string input, bool run, bool @private) {
            object[] results = this.Invoke("createSubmission", new object[] {
                        user,
                        pass,
                        sourceCode,
                        language,
                        input,
                        run,
                        @private});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void createSubmissionAsync(string user, string pass, string sourceCode, int language, string input, bool run, bool @private) {
            this.createSubmissionAsync(user, pass, sourceCode, language, input, run, @private, null);
        }
        
        /// <remarks/>
        public void createSubmissionAsync(string user, string pass, string sourceCode, int language, string input, bool run, bool @private, object userState) {
            if ((this.createSubmissionOperationCompleted == null)) {
                this.createSubmissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSubmissionOperationCompleted);
            }
            this.InvokeAsync("createSubmission", new object[] {
                        user,
                        pass,
                        sourceCode,
                        language,
                        input,
                        run,
                        @private}, this.createSubmissionOperationCompleted, userState);
        }
        
        private void OncreateSubmissionOperationCompleted(object arg) {
            if ((this.createSubmissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSubmissionCompleted(this, new createSubmissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ideone.com/api/1/service#getSubmissionStatus", RequestNamespace="http://ideone.com/api/1/service", ResponseNamespace="http://ideone.com/api/1/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getSubmissionStatus(string user, string pass, string link) {
            object[] results = this.Invoke("getSubmissionStatus", new object[] {
                        user,
                        pass,
                        link});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getSubmissionStatusAsync(string user, string pass, string link) {
            this.getSubmissionStatusAsync(user, pass, link, null);
        }
        
        /// <remarks/>
        public void getSubmissionStatusAsync(string user, string pass, string link, object userState) {
            if ((this.getSubmissionStatusOperationCompleted == null)) {
                this.getSubmissionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubmissionStatusOperationCompleted);
            }
            this.InvokeAsync("getSubmissionStatus", new object[] {
                        user,
                        pass,
                        link}, this.getSubmissionStatusOperationCompleted, userState);
        }
        
        private void OngetSubmissionStatusOperationCompleted(object arg) {
            if ((this.getSubmissionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubmissionStatusCompleted(this, new getSubmissionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ideone.com/api/1/service#getSubmissionDetails", RequestNamespace="http://ideone.com/api/1/service", ResponseNamespace="http://ideone.com/api/1/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getSubmissionDetails(string user, string pass, string link, bool withSource, bool withInput, bool withOutput, bool withStderr, bool withCmpinfo) {
            object[] results = this.Invoke("getSubmissionDetails", new object[] {
                        user,
                        pass,
                        link,
                        withSource,
                        withInput,
                        withOutput,
                        withStderr,
                        withCmpinfo});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getSubmissionDetailsAsync(string user, string pass, string link, bool withSource, bool withInput, bool withOutput, bool withStderr, bool withCmpinfo) {
            this.getSubmissionDetailsAsync(user, pass, link, withSource, withInput, withOutput, withStderr, withCmpinfo, null);
        }
        
        /// <remarks/>
        public void getSubmissionDetailsAsync(string user, string pass, string link, bool withSource, bool withInput, bool withOutput, bool withStderr, bool withCmpinfo, object userState) {
            if ((this.getSubmissionDetailsOperationCompleted == null)) {
                this.getSubmissionDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubmissionDetailsOperationCompleted);
            }
            this.InvokeAsync("getSubmissionDetails", new object[] {
                        user,
                        pass,
                        link,
                        withSource,
                        withInput,
                        withOutput,
                        withStderr,
                        withCmpinfo}, this.getSubmissionDetailsOperationCompleted, userState);
        }
        
        private void OngetSubmissionDetailsOperationCompleted(object arg) {
            if ((this.getSubmissionDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubmissionDetailsCompleted(this, new getSubmissionDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ideone.com/api/1/service#getLanguages", RequestNamespace="http://ideone.com/api/1/service", ResponseNamespace="http://ideone.com/api/1/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getLanguages(string user, string pass) {
            object[] results = this.Invoke("getLanguages", new object[] {
                        user,
                        pass});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getLanguagesAsync(string user, string pass) {
            this.getLanguagesAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void getLanguagesAsync(string user, string pass, object userState) {
            if ((this.getLanguagesOperationCompleted == null)) {
                this.getLanguagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLanguagesOperationCompleted);
            }
            this.InvokeAsync("getLanguages", new object[] {
                        user,
                        pass}, this.getLanguagesOperationCompleted, userState);
        }
        
        private void OngetLanguagesOperationCompleted(object arg) {
            if ((this.getLanguagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLanguagesCompleted(this, new getLanguagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ideone.com/api/1/service#testFunction", RequestNamespace="http://ideone.com/api/1/service", ResponseNamespace="http://ideone.com/api/1/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] testFunction(string user, string pass) {
            object[] results = this.Invoke("testFunction", new object[] {
                        user,
                        pass});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void testFunctionAsync(string user, string pass) {
            this.testFunctionAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void testFunctionAsync(string user, string pass, object userState) {
            if ((this.testFunctionOperationCompleted == null)) {
                this.testFunctionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestFunctionOperationCompleted);
            }
            this.InvokeAsync("testFunction", new object[] {
                        user,
                        pass}, this.testFunctionOperationCompleted, userState);
        }
        
        private void OntestFunctionOperationCompleted(object arg) {
            if ((this.testFunctionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testFunctionCompleted(this, new testFunctionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void createSubmissionCompletedEventHandler(object sender, createSubmissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSubmissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSubmissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void getSubmissionStatusCompletedEventHandler(object sender, getSubmissionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubmissionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubmissionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void getSubmissionDetailsCompletedEventHandler(object sender, getSubmissionDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubmissionDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubmissionDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void getLanguagesCompletedEventHandler(object sender, getLanguagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLanguagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLanguagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void testFunctionCompletedEventHandler(object sender, testFunctionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testFunctionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testFunctionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591